# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190202_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_count',
        ),
    ]
